# Generated by Django 4.0 on 2022-05-19 13:02

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.blockchain.fields
import hub20.apps.ethereum_money.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('ethereum_money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdWallet',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchain.baseethereumaccount')),
            ],
            bases=('blockchain.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='HierarchicalDeterministicWallet',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchain.baseethereumaccount')),
                ('index', models.PositiveIntegerField(unique=True)),
            ],
            bases=('blockchain.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='KeystoreAccount',
            fields=[
                ('baseethereumaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blockchain.baseethereumaccount')),
                ('private_key', hub20.apps.blockchain.fields.HexField(max_length=64, unique=True)),
            ],
            bases=('blockchain.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blockchain.baseethereumaccount',),
        ),
        migrations.CreateModel(
            name='WalletBalanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', hub20.apps.ethereum_money.fields.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_records', to='blockchain.baseethereumaccount')),
            ],
            options={
                'unique_together': {('wallet', 'currency', 'block')},
            },
        ),
    ]
