# Generated by Django 3.2.9 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethereum_money", "0001_initial"),
    ]

    operations = [
        migrations.RenameField("ethereumtoken", "code", "symbol"),
        migrations.AlterField(
            model_name="ethereumtoken",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
    ]
