# Generated by Django 3.2.9 on 2021-12-13 14:27

from django.db import migrations

from hub20.apps.ethereum_money.fields import TokenlistStandardURLField


class Migration(migrations.Migration):

    dependencies = [
        ("ethereum_money", "0002_auto_20211213_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethereumtoken",
            name="logoURI",
            field=TokenlistStandardURLField(null=True),
        ),
    ]
