# Generated by Django 4.0 on 2022-02-16 11:58

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.blockchain.fields
import hub20.apps.ethereum_money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('ethereum_money', '0002_uuidtaggeditem_alter_tokenlist_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', hub20.apps.ethereum_money.fields.EthereumTokenAmountField(decimal_places=18, max_digits=32)),
                ('sender', hub20.apps.blockchain.fields.EthereumAddressField()),
                ('recipient', hub20.apps.blockchain.fields.EthereumAddressField()),
                ('log_index', models.SmallIntegerField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='blockchain.transaction')),
            ],
            options={
                'ordering': ('transaction', 'log_index'),
                'unique_together': {('transaction', 'log_index')},
            },
        ),
    ]
