# Generated by Django 4.0 on 2022-01-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0005_remove_hierarchicaldeterministicwallet_baseethereumaccount_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_lists', to='auth.user')),
                ('tokens', models.ManyToManyField(to='ethereum_money.EthereumToken')),
            ],
            options={
                'unique_together': {('name', 'created_by')},
            },
        ),
    ]
