# Generated by Django 4.0 on 2022-01-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0006_usertokenlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertokenlist',
            unique_together={('created_by', 'name')},
        ),
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('tokens', models.ManyToManyField(related_name='lists', to='ethereum_money.EthereumToken')),
            ],
        ),
        migrations.AddField(
            model_name='usertokenlist',
            name='token_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_managed', to='ethereum_money.tokenlist'),
        ),
    ]
