# Generated by Django 4.0 on 2022-01-20 19:14

from django.db import migrations


def copy_token_lists(apps, schema_editor):
    TokenList = apps.get_model("ethereum_money", "TokenList")
    UserTokenList = apps.get_model("ethereum_money", "UserTokenList")

    for user_token_list in UserTokenList.objects.all():
        token_list, _ = TokenList.objects.get_or_create(
            name=user_token_list.name, defaults={"description": user_token_list.description}
        )
        token_list.tokens.set(user_token_list.tokens.all())
        user_token_list.token_list = token_list
        user_token_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ethereum_money", "0007_alter_usertokenlist_unique_together_tokenlist_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_token_lists, migrations.RunPython.noop),
    ]
