# Generated by Django 4.0 on 2022-01-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0008_migrate_user_tokenlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertokenlist',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usertokenlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usertokenlist',
            name='token_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_managed', to='ethereum_money.tokenlist'),
        ),
        migrations.AlterUniqueTogether(
            name='usertokenlist',
            unique_together={('user', 'token_list')},
        ),
        migrations.RemoveField(
            model_name='usertokenlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usertokenlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usertokenlist',
            name='tokens',
        ),
    ]
