# Generated by Django 4.0 on 2022-01-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_store_accepted_token_list'),
        ('ethereum_money', '0010_stabletokenpair'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertokenlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertokenlist',
            name='token_list',
        ),
        migrations.RemoveField(
            model_name='usertokenlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='TokenList',
        ),
        migrations.DeleteModel(
            name='UserTokenList',
        ),
    ]
