# Generated by Django 4.0 on 2022-01-23 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub20.apps.ethereum_money.fields
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0011_alter_usertokenlist_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('tokens', models.ManyToManyField(related_name='%(app_label)s_%(class)s_tokenlists', to='ethereum_money.EthereumToken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token_lists', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('url', hub20.apps.ethereum_money.fields.TokenlistStandardURLField()),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('tokens', models.ManyToManyField(related_name='%(app_label)s_%(class)s_tokenlists', to='ethereum_money.EthereumToken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
