# Generated by Django 4.0 on 2022-01-24 00:50

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.ethereum_money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0012_usertokenlist_tokenlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtoken',
            name='logoURI',
            field=hub20.apps.ethereum_money.fields.TokenlistStandardURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertokenlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_lists', to='auth.user'),
        ),
    ]
