# Generated by Django 4.0 on 2022-01-24 03:34

from django.db import migrations
import hub20.apps.ethereum_money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0014_tokenlist_version_alter_tokenlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtoken',
            name='logoURI',
            field=hub20.apps.ethereum_money.fields.TokenlistStandardURLField(blank=True, max_length=512, null=True),
        ),
    ]
