# Generated by Django 3.2.3 on 2021-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0002_channeldeposit_channelwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiden',
            name='url',
            field=models.URLField(default='http://raiden:5001', unique=True),
            preserve_default=False,
        ),
    ]
