# Generated by Django 3.2.9 on 2021-12-01 00:49

from django.db import migrations
import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raiden', '0003_raiden_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelwithdraw',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelwithdraw',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='channelwithdraw',
            name='transaction',
        ),
        migrations.AddField(
            model_name='raidenmanagementorder',
            name='transaction_hash',
            field=hub20.apps.blockchain.fields.HexField(max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ChannelDeposit',
        ),
        migrations.DeleteModel(
            name='ChannelWithdraw',
        ),
    ]
