# Generated by Django 3.2.9 on 2021-12-16 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0018_web3provider_requires_geth_poa_middleware'),
        ('raiden', '0004_auto_20211201_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepositcontractorder',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deposit_orders', to='blockchain.chain'),
        ),
    ]
