# Generated by Django 4.0 on 2022-01-13 22:50

from django.db import migrations, models
import django.db.models.deletion
import hub20.apps.raiden.models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0018_web3provider_requires_geth_poa_middleware'),
        ('raiden', '0007_alter_userdepositcontractorder_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiden',
            name='web3_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.web3provider'),
        ),
        migrations.AlterField(
            model_name='raiden',
            name='url',
            field=hub20.apps.raiden.models.RaidenURLField(unique=True),
        ),
    ]
