# Generated by Django 3.2.3 on 2021-10-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.chain'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('hash', 'chain')},
        ),
    ]
