# Generated by Django 4.0 on 2022-04-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='is_mainnet',
        ),
        migrations.CreateModel(
            name='ChainMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='blockchain.chain')),
                ('rollup_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='blockchain.chain')),
                ('sidechain_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidechains', to='blockchain.chain')),
                ('testing_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testnets', to='blockchain.chain')),
            ],
        ),
    ]
