# Generated by Django 4.0 on 2022-04-04 15:30

from django.db import migrations


def create_metadata_record(apps, schema_editor):
    Chain = apps.get_model("blockchain", "Chain")
    ChainMetadata = apps.get_model("blockchain", "ChainMetadata")

    for chain in Chain.objects.all():
        ChainMetadata.objects.get_or_create(chain=chain)


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0002_remove_chain_is_mainnet_chainmetadata"),
    ]

    operations = [migrations.RunPython(create_metadata_record, migrations.RunPython.noop)]
