# Generated by Django 3.2.3 on 2021-10-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_record_chain_in_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.chain'),
        ),
    ]
