# Generated by Django 4.0 on 2022-04-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_chainmetadata_rollup_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web3provider',
            name='max_block_scan_range',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
