# Generated by Django 3.2.9 on 2021-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_transaction_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
