# Generated by Django 4.0 on 2022-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_web3provider_max_block_scan_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainmetadata',
            name='short_name',
            field=models.SlugField(null=True),
        ),
    ]
