# Generated by Django 3.2.9 on 2021-11-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_chain_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
