# Generated by Django 3.2.9 on 2021-12-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_explorer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web3provider',
            name='chain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='blockchain.chain'),
        ),
    ]
