# Generated by Django 3.2.9 on 2021-12-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_alter_web3provider_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='is_mainnet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='name',
            field=models.CharField(default='EVM-compatible network', max_length=128),
        ),
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='NativeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('symbol', models.CharField(max_length=16)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='native_token', to='blockchain.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
