# Generated by Django 3.2.9 on 2021-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_auto_20211212_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
