# Generated by Django 3.2.9 on 2021-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_alter_chain_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='web3provider',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='explorer',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='web3provider',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='explorer',
            unique_together={('url', 'chain')},
        ),
    ]
