# Generated by Django 3.2.9 on 2021-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_auto_20211212_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='explorer',
            name='standard',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
