# Generated by Django 3.2.9 on 2021-12-13 12:19

from django.db import migrations
import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0013_auto_20211212_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web3provider',
            name='url',
            field=hub20.apps.blockchain.fields.Web3ProviderURLField(),
        ),
    ]
