# Generated by Django 3.2.9 on 2021-12-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_alter_web3provider_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={'ordering': ('id',)},
        ),
    ]
