# Generated by Django 3.2.9 on 2021-12-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0015_alter_chain_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web3provider',
            old_name='enabled',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='block',
            name='base_fee_per_gas',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='web3provider',
            name='supports_eip1559',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='web3provider',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='blockchain.chain'),
        ),
    ]
