# Generated by Django 3.2.9 on 2021-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20211214_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='web3provider',
            name='client_version',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web3provider',
            name='supports_pending_filters',
            field=models.BooleanField(default=False),
        ),
    ]
