# Generated by Django 3.2.9 on 2021-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0017_auto_20211214_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='web3provider',
            name='requires_geth_poa_middleware',
            field=models.BooleanField(default=False),
        ),
    ]
