# Generated by Django 4.0 on 2022-01-18 10:00

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import django.db.models.expressions
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models

import hub20.apps.blockchain.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0018_web3provider_requires_geth_poa_middleware"),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name="TransactionDataRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hash", hub20.apps.blockchain.fields.HexField(db_index=True, max_length=64)),
                ("from_address", hub20.apps.blockchain.fields.EthereumAddressField(db_index=True)),
                ("to_address", hub20.apps.blockchain.fields.EthereumAddressField(db_index=True)),
                ("data", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="transactionlog",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="transactionlog",
            name="transaction",
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt",
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("hash", "block"), name="unique_tx_per_block"
            ),
        ),
        migrations.DeleteModel(
            name="TransactionLog",
        ),
        migrations.AddField(
            model_name="transactiondatarecord",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_data",
                to="blockchain.chain",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactiondatarecord",
            unique_together={("hash", "chain")},
        ),
    ]
