# Generated by Django 4.0 on 2022-01-18 16:45

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0020_split_transaction_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="data",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gas_price",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gas_used",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="index",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="nonce",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="success",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="value",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
