# Generated by Django 4.0 on 2022-01-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0021_remove_transaction_chain_remove_transaction_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_block', models.PositiveBigIntegerField(default=1)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexers', to='blockchain.chain')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventindexer',
            constraint=models.UniqueConstraint(fields=('chain', 'name'), name='unique_name_per_chain'),
        ),
    ]
