# Generated by Django 4.0 on 2022-02-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ethereum_money', '0002_uuidtaggeditem_alter_tokenlist_keywords_and_more'),
        ('core', '0001_initial'),
        ('raiden', '0001_initial'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidenclientaccount',
            name='raiden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raiden_account', to='raiden.raiden'),
        ),
        migrations.AddField(
            model_name='paymentroute',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.deposit'),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken'),
        ),
        migrations.AddField(
            model_name='payment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentroute'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='debit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='core.book'),
        ),
        migrations.AddField(
            model_name='debit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken'),
        ),
        migrations.AddField(
            model_name='debit',
            name='reference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='credit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.book'),
        ),
        migrations.AddField(
            model_name='credit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ethereum_money.ethereumtoken'),
        ),
        migrations.AddField(
            model_name='credit',
            name='reference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='book',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='ethereum_money.ethereumtoken'),
        ),
        migrations.AddField(
            model_name='raidenwithdrawalconfirmation',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raiden.payment'),
        ),
        migrations.AddField(
            model_name='raidenpaymentroute',
            name='raiden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_routes', to='raiden.raiden'),
        ),
        migrations.AddField(
            model_name='raidenpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raiden.payment'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers_received', to='auth.user'),
        ),
        migrations.AlterUniqueTogether(
            name='debit',
            unique_together={('book', 'reference_type', 'reference_id')},
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('book', 'reference_type', 'reference_id')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('token', 'owner_type', 'owner_id')},
        ),
        migrations.AddField(
            model_name='blockchainwithdrawalreceipt',
            name='transaction_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transactiondatarecord'),
        ),
        migrations.AddField(
            model_name='blockchainwithdrawalconfirmation',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction'),
        ),
        migrations.AddField(
            model_name='blockchainpaymentroute',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_routes', to='blockchain.baseethereumaccount'),
        ),
        migrations.AddField(
            model_name='blockchainpaymentroute',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.chain'),
        ),
        migrations.AddField(
            model_name='blockchainpayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction'),
        ),
        migrations.CreateModel(
            name='BlockchainWithdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawal',),
        ),
        migrations.CreateModel(
            name='RaidenWithdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawal',),
        ),
        migrations.AlterUniqueTogether(
            name='raidenpaymentroute',
            unique_together={('raiden', 'identifier')},
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('paymentorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.paymentorder')),
                ('external_identifier', models.TextField()),
                ('requester_ip', models.GenericIPAddressField(null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.paymentorder',),
        ),
    ]
