# Generated by Django 3.2.9 on 2021-12-11 21:26

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import hub20.apps.core.models.payments


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211027_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainpaymentroute',
            name='payment_window',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='raidenpaymentroute',
            name='payment_window',
            field=models.DurationField(default=hub20.apps.core.models.payments.calculate_raiden_payment_window),
        ),
    ]
