# Generated by Django 4.0 on 2022-05-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('raiden', '0001_initial'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidenwithdrawalconfirmation',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raiden.payment'),
        ),
        migrations.AddField(
            model_name='raidenpaymentroute',
            name='raiden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_routes', to='raiden.raiden'),
        ),
        migrations.AddField(
            model_name='raidenpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raiden.payment'),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers_received', to='auth.user'),
        ),
        migrations.AlterUniqueTogether(
            name='debit',
            unique_together={('book', 'reference_type', 'reference_id')},
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('book', 'reference_type', 'reference_id')},
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='core.paymentorder'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('token', 'owner_type', 'owner_id')},
        ),
        migrations.AddField(
            model_name='blockchainwithdrawalreceipt',
            name='transaction_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transactiondatarecord'),
        ),
        migrations.AddField(
            model_name='blockchainwithdrawalconfirmation',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction'),
        ),
        migrations.AddField(
            model_name='blockchainpaymentroute',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_routes', to='blockchain.baseethereumaccount'),
        ),
        migrations.AddField(
            model_name='blockchainpayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction'),
        ),
        migrations.CreateModel(
            name='BlockchainWithdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawal',),
        ),
        migrations.CreateModel(
            name='RaidenWithdrawal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.withdrawal',),
        ),
    ]
