# Generated by Django 4.0 on 2022-01-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211211_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='accepted_currencies',
        ),
    ]
