# Generated by Django 4.0 on 2022-01-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0007_alter_usertokenlist_unique_together_tokenlist_and_more'),
        ('core', '0004_remove_store_accepted_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accepted_token_list',
            field=models.ForeignKey(help_text='The list of tokens that will be accepted for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethereum_money.tokenlist'),
        ),
    ]
