# Generated by Django 4.0 on 2022-01-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0009_rename_created_by_usertokenlist_user_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_store_accepted_token_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.ManyToManyField(to='ethereum_money.EthereumToken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='auth.user')),
            ],
        ),
    ]
