# Generated by Django 4.0 on 2022-01-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='accepted_token_list',
        ),
    ]
