# Generated by Django 4.0 on 2022-01-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_money', '0012_usertokenlist_tokenlist'),
        ('core', '0007_remove_store_accepted_token_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accepted_token_list',
            field=models.ForeignKey(help_text='The list of tokens that will be accepted for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ethereum_money.usertokenlist'),
        ),
    ]
