# Generated by Django 4.0 on 2022-05-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erc20TokenTransferIndexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_block', models.PositiveBigIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erc20_transfer_indexer', to='ethereum.basewallet')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_indexers', to='ethereum.chain')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_indexer', to='ethereum.erc20token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NativeTokenTransferIndexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_block', models.PositiveBigIntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_token_transfer_indexer', to='ethereum.basewallet')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_indexers', to='ethereum.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EventIndexer',
        ),
    ]
